---

- name: Initial Server Setup
  hosts: HomeServer
  become: true

  vars_prompt:
    - name: sambapresent
      prompt: "Do you own a Samba share ? [y/n] "

  tasks:

    - name: Prompt for Samba username
      pause:
        prompt: "Enter your smb username: "
      when: sambapresent == "y"
      register: smbUsername

    - name: Prompt for Samba password
      pause:
        prompt: "Enter your smb password: "
      when: sambapresent == "y"
      register: smbPassword

    - name: Prompt for Samba Path
      pause:
        prompt: "Enter your smb Path (ip:/sharelocation): "
      when: sambapresent == "y"
      register: shareLocation

    - name: Install CIFS-Utils for Samba Share
      when: sambapresent == "y"
      ansible.builtin.apt:
        name: cifs-utils
        state: present

    # Mount Smb drive
    - name: Mount SMB Share
      when: sambapresent == "y" and username != "" and password != ""
      ansible.posix.mount:
        src: '{{ shareLocation }}'
        path: /mnt/nfs
        fstype: cifs
        opts: 'username={{ smbUsername }},password={{ smbPassword }}'
        state: mounted
        boot: true

    - name: Install Docker dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - pip
          - python3
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - containerd
          - docker.io
          - docker-compose
        state: present

    - name: Install PIP Docker
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
          - jsondiff

    # To do
    # Create Group named Docker
    - name: Create Docker Group

    # To do
    # Append User to Docker Group
    - name: Append User to Docker Group

    - name: Install Jellyfin
      ansible.builtin.apt:
        name:
          - jellyfin
        state: present

    - name: Install Plex
      community.general.snap:
        name:
          - plexmediaserver
        state: present
