---
version: '3.8'
name: "mediaserver"
services: 
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${configs}/transmission:/config
      # Volume Used for Automation (Sonarr / Radarr)
      - ${downloads}:/downloads/complete 
      # Volume Used for Manual Control
      - ${movies}:/Movies
      - ${tvShows}:/Tv
    ports:
      - '9091:9091'
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - '8989:8989'
    volumes:
      - ${configs}/sonarr:/config
      # Manual Folder Mapping /downloads = /downloads/complete needed in Sonarr when appending Torrent Client
      - ${downloads}:/downloads
      - ${tvShows}:/downloads/Tv
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - '7878:7878'
    volumes:
      - ${configs}/radarr:/config
      - ${downloads}:/downloads
      - ${movies}:/downloads/Movies
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Zurich
    ports:
      - '5055:5055'
    volumes:
      - ${configs}/overseer:/app/config
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - '9696:9696'
    volumes:
      - ${configs}/prowlarr:/config
    restart: unless-stopped
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '3000:3000'
    volumes:
      - ${configs}/adguardhome:/opt/adguardhome/work
      - ${configs}/adguardhome:/opt/adguardhome/conf
    restart: unless-stopped
  dozzle:
    container_name dozzle
    image: amir20/dozzle:latest
    ports:
      - '8888:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${configs}//nginxrevproxy:/data
      - ${configs}//nginxrevproxy/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: '${proxymanager}'
networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: ${vlaninterface}
    ipam:
      config:
        - subnet: '${vlansubnet}'
          ip_range: '${vlaniprange}'
          gateway: '${vlangateway}'
