---
services: 
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${configs}/transmission:/config
      # Volume Used for Automation (Sonarr / Radarr)
      - ${downloads}:/downloads/complete 
      # Volume Used for Manual Control
      - ${movies}:/Movies
      - ${tvShows}:/Tv
    ports:
      - '9091:9091'
    restart: unless-stopped
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    volumes:
      - ${configs}/jdownloader:/config
      - ${downloads}/complete:/output:rw