---
version: '3.5'
services:

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${configs}Transmission:/config
      - ${downloads}:/downloads
      - ${movies}:/downloads/Movies
      - ${tvShows}:/downloads/Tv
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 8989:8989
    volumes:
      - ${configs}Sonarr:/config
      - ${downloads}:/downloads
      - ${movies}:/downloads/Movies
      - ${tvShows}:/downloads/Tv
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 7878:7878
    volumes:
      - ${configs}Radarr:/config
      - ${downloads}:/downloads
      - ${movies}:/downloads/Movies
      - ${tvShows}:/downloads/Tv
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 9696:9696
    volumes:
      - ${configs}Prowlarr:/config
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped





