---
version: '3.8'
services:

  transmissionmovies:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmissionmovie
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${configs}Transmission-Movies:/config
      - ${movies}:/downloads/complete
    ports:
      - 9091:9091
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmissionmovie.rule=Host(`transmission-movie.localhost`)"
    depends_on:
      - traefik
    restart: unless-stopped

  transmissiontv:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmissiontv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${configs}Transmission-TV:/config
      - ${downloads}:/downloads/complete
      - ${tvShows}:/downloads/Tv
    ports:
      - 9092:9091
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmissiontv.rule=Host(`transmission-tv.localhost`)"
    depends_on:
      - traefik
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 8989:8989
    volumes:
      - ${configs}Sonarr:/config
      - ${downloads}:/downloads
      - ${tvShows}:/downloads/Tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.localhost`)"
    depends_on:
      - traefik
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 7878:7878
    volumes:
      - ${configs}Radarr:/config
      - ${downloads}:/downloads
      - ${movies}:/downloads/Movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.localhost`)"
    depends_on:
      - traefik
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 9696:9696
    volumes:
      - ${configs}Prowlarr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.localhost`)"
    depends_on:
      - traefik
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.watchtower.rule=Host(`watchtower.localhost`)"
    depends_on:
      - traefik
    restart: unless-stopped

  traefik:
    image: traefik:v2.10
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    restart: unless-stopped






