---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
      - TZ=Europe/Zurich
    volumes:
      - /mnt/nfs/docker_config/singleTorrent:/config
      - /mnt/nfs/Downloads/:/downloads
      - /mnt/nfs/Movies:/Movies
      - /mnt/nfs/Tv/sonarr:/Tv
    ports:
      - 9095:9091
    restart: unless-stopped
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    volumes:
      - ~/jdownloader:/config
      - /mnt/nfs/tmp:/output
    ports:
      - 5800:5800
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
      - TZ=Europe/Zurich
      - WEBUI_PORT=9090
    volumes:
      - ~/qbittorrent:/config
      - /mnt/nfs/Downloads:/downloads
    ports:
      - 9090:9090
    restart: unless-stopped
