---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:4.0.6
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
      - TZ=Europe/Zurich
    volumes:
      - ~/singleTorrent:/config
      - ~/Transmission-WebGui:/usr/share/transmission/public_html
      - /mnt/nfs/Downloads/:/downloads
      - /mnt/nfs/Movies:/Movies
      - /mnt/nfs/Tv/sonarr:/Tv
    ports:
      - 9095:9091
    restart: unless-stopped
  jdownloader:
    image: jlesage/jdownloader-2:v26.01.1
    container_name: jdownloader
    volumes:
      - ~/jdownloader:/config
      - /mnt/nfs/tmp:/output
    ports:
      - 5800:5800
      - 5900:5900
      - 3128:3128
      - 9666:9666
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
      - TZ=Europe/Zurich
      - WEBUI_PORT=9090
    volumes:
      - ~/qbittorrent:/config
      - /mnt/nfs/Downloads:/downloads
    ports:
      - 9090:9090
    restart: unless-stopped
