---
name: media-stack
services:
  # radarr:
  #   image: lscr.io/linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Zurich
  #     - LOG_LEVEL=info
  #   ports:
  #     - 7878:7878
  #   volumes:
  #     - ~/radarr:/config
  #     - /mnt/nfs/Downloads/:/downloads
  #     - /mnt/nfs/Movies/:/movies
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - LOG_LEVEL=info
    ports:
      - 8989:8989
    volumes:
      - ~/sonarr:/config
      - /mnt/nfs/Tv/sonarr/:/tv
      - /mnt/nfs/Downloads/:/downloads
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - LOG_LEVEL=info
    ports:
      - 9696:9696
    volumes:
      - ~/prowlarr:/config
    restart: unless-stopped
  jellyseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Zurich
      - LOG_LEVEL=info
    ports:
      - 5055:5055
    volumes:
      - ~/jellyserr:/app/config
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    restart: unless-stopped


