---
services:
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    ports:
      - "9080:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    restart: unless-stopped
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.10.2
    container_name: node_exporter
    pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    networks:
      - monitoring
  c-advisor:
    image: gcr.io/cadvisor/cadvisor:0.55.1
    container_name: c-advisor
    privileged: true
    devices:
      - /dev/kmsg
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring
    restart: unless-stopped
  loki:
    image: grafana/loki:3.6.3
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki.yml:/mnt/config/loki-config.yml
    networks:
      - monitoring
    restart: unless-stopped
  alloy:
    image: grafana/alloy:1.12.2
    container_name: alloy
    volumes:
      - ./configs/alloy.config:/etc/alloy/config.alloy
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/log:/var/log:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 12345:12345
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    networks:
      - monitoring
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss:12.3.1
    user: '1000'
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3030:3000'
    volumes:
      - '~/grafana:/var/lib/grafana'
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge

