---
services: 
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 8888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped