---
services: 
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000
    volumes:
      - ${configs}/adguardhome:/opt/adguardhome/work
      - ${configs}/adguardhome:/opt/adguardhome/conf
    restart: unless-stopped
  wireguardvpn:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    environment:
      - LANG=en
      - HOSTNAME=wireguard
      - PASSWORD=PRlc15J!!
      # Password is deprecated see:
      #  - https://github.com/wg-easy/wg-easy/tree/master?tab=readme-ov-file#2-run-wireguard-easy
      #  - https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
      - WG_HOST=${hostip}
      - WG_ALLOWED_IPS=10.8.0.0/24 , ${hostnetwork}
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_HOST=${publicip}
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=192.168.0.x
    volumes:
      - ${configs}/wg-easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman 
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
