---
services: 
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000
    volumes:
      - ~/adguardhome:/opt/adguardhome/work
      - ~/adguardhome:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3
  wireguardvpn:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    environment:
      - LANG=en
      - HOSTNAME=wireguard
      - PASSWORD_HASH=$$2a$$12$$ViQ.M.kl3OkL5cD/Vgde1Oy.8wEBQAiWob.PU2qd0WtrX4xmSofOq
      # Password is deprecated see:
      #  - https://github.com/wg-easy/wg-easy/tree/master?tab=readme-ov-file#2-run-wireguard-easy
      #  - https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
      - WG_HOST=84.73.196.77
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - PORT=51821
      - WG_PORT=51820
    volumes:
      - ~/wireguard:/etc/wireguard
    restart: unless-stopped    
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman 
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/28