services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:1.45.0-plus
    ports:
      - 50555550:9090
    volumes:
      - ~/linkding:/etc/linkding/data
    restart: unless-stopped
