---
- name: Load Homeserver Services
  hosts: HomeServer
  become: true

  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: compose
        dest: /var
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0775'
    - name: Start Containers
      community.docker.docker_compose:
        project_src: /var/compose
        files:
          - docker-compose.yml
